const pool = require("../db");

class UserTypeModel {
    async createTable() {
        await pool.query(`
            CREATE TABLE IF NOT EXISTS user_types (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(30) NOT NULL
            );
        `)
        console.log(`Table user_types was created successfully!`);
    }

    async selectAllByName(name) {
        const {rows} =  await pool.query(
            `SELECT * FROM user_types WHERE name = $1`,
            [name]
        );
        return rows.length > 0 ? rows[0] : null
    }

    async selectOneIdByName(name) {
        const {rows} =  await pool.query(
            `SELECT id FROM user_types WHERE name = $1`,
            [name]
        );
        return rows.length > 0 ? rows[0].id : null
    }

    async insert(values) {
        const {rows} = await pool.query(
            `INSERT INTO user_types(name) VALUES ($1) RETURNING *`,
            values
        )
        return rows.length > 0 ? rows[0] : null
    }
}

module.exports = UserTypeModel;