const pool = require("../db");

class UserModel{
    async createTable() {
        await pool.query(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                last_name VARCHAR(30) NOT NULL,
                first_name VARCHAR(30) NOT NULL,
                email VARCHAR(100) NOT NULL UNIQUE,
                password VARCHAR(200) NOT NULL,
                id_user_type INTEGER NOT NULL,
                CONSTRAINT fk_user_types FOREIGN KEY(id_user_type) REFERENCES user_types(id)
            );
        `)
        console.log(`Table users was created successfully!`);
    }

    async selectOneByEmail(email) {
        const {rows} =  await pool.query(
            `SELECT * FROM users WHERE email = $1`,
            [email]
        );
        return rows.length > 0 ? rows[0] : null
    }

    async insert(values) {
        const {rows} = await pool.query(
            `INSERT INTO users(last_name, first_name, email, password, id_user_type) VALUES ($1, $2, $3, $4, $5) RETURNING *`,
            values
        )
        return rows.length > 0 ? rows[0] : null
    }
}

module.exports = UserModel;